In [2]:
import torch

In [25]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.1980,  0.4509, -2.4318], requires_grad=True)


In [26]:
y = x + 2
print(y)

tensor([ 0.8020,  2.4509, -0.4318], grad_fn=<AddBackward0>)


In [27]:
z = y * y * 2
z = z.mean()
print(z)

tensor(4.5579, grad_fn=<MeanBackward0>)


In [29]:
# v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
# 
# z.backw ard() # dz / dx
# print(x.grad)

SyntaxError: invalid syntax (1982236826.py, line 3)

In [38]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.data.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [41]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights , lr = 0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [ ]:
weights = torch.ones(4, requires_grad=True)


z.backward(
    
)